name: AMinecraftPlugin
version: '${project.version}'
main: aminecraftplugin.aminecraftplugin.Main
api-version: 1.19
authors: [ Duffie13, Vermulst ]
commands:
  addresource:
    description: add new resource to the game
    usage: /addresource
    aliases:
      - resources
  addvalue:
    description: add value to item in hand
    usage: /addvalue
  createmarket:
    description: create a market
    usage: /createmarket (name)
  removemarket:
    description: removes a market
    usage: /removemarket
  createloottable:
    description: create a loot table with name
    usage: /createloottable <name>
  checkloottables:
    description: check loot tables
    usage: /checkloottables
