name: AMinecraftPlugin
version: '${project.version}'
main: aminecraftplugin.aminecraftplugin.Main
api-version: 1.19
authors: [ Duffie13, Vermulst ]
softdepend: [HolographicDisplays, ProtocolLib, Citizens]
commands:
  addresource:
    permission: drilz.operator
    description: add new resource to the game
    usage: /addresource
    aliases:
      - resources
  addvalue:
    permission: drilz.operator
    description: add value to item in hand
    usage: /addvalue
  addmaterial:
    permission: drilz.operator
    description: add material
    usage: /addmaterial
  addmoney:
    permission: drilz.operator
    description: add money
    usage: /addmoney <double>
  createmarket:
    permission: drilz.operator
    description: create a market
    usage: /createmarket <name>
  removemarket:
    permission: drilz.operator
    description: removes a market
    usage: /removemarket
  createloottable:
    permission: drilz.operator
    description: create a loot table with name
    usage: /createloottable <name>
  checkloottables:
    permission: drilz.operator
    description: check loot tables
    usage: /checkloottables
  getDrill:
    permission: drilz.operator
    description: get drill with command
    usage: /getdrill <tier> <structurename>
  backpack:
    description: open your backpack
    usage: /backpack
  miningResourceMenu:
    description: open the menu where you can add/remove mining resources
    usage: /miningResourceMenu
  setspawn:
    description: set spawn with a name
    usage: /setspawn <name>
  removespawn:
    description: remove a spawn with name
    usage: /removespawn <name>

permissions:
  drilz.operator:
    default: op
