name: AMinecraftPlugin
version: '${project.version}'
main: aminecraftplugin.aminecraftplugin.Main
api-version: 1.19
authors: [ Duffie13, Vermulst ]
commands:
  addresource:
    description: add new resource to the game
    usage: /addresource
  addvalue:
    description: add value to item in hand
    usage: /addvalue
  CreateMarket:
    description: create a market
    usage: /createmarket
